# Generated by Django 3.0.4 on 2020-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0027_event_eventproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='defaultEvent.jpg', upload_to='event_pics'),
        ),
    ]
